#pragma once

#include <raylib.h>

// == NUMERIC SETTINGS ==
#define DEFAULT_WINDOW_WIDTH 720
#define DEFAULT_WINDOW_HEIGHT 720
#define TARGET_FPS 60
#define BOARD_SIZE_AXIS 3
#define WINNER_SIZE_AXIS 3

// == STRING SETTINGS ==
#define WINDOW_TITLE "Tic Tac Toe"
#define WINDOW_FLAGS FLAG_WINDOW_RESIZABLE
#define EXIT_KEY KEY_NULL
#define RESTART_KEY KEY_ESCAPE
#define STARTING_TURN 'X'

// == COLOR SETTINGS ==
#define COLOR_WINDOW_BG BLACK
#define COLOR_BOARD_TILE WHITE
#define COLOR_FG BLACK
#define COLOR_TEXT_FG WHITE
